- name: task level variables
  hosts:  web
  vars:
    NAME: "MOKA"
    COURSE: "DEVOPS"
  tasks:
  - name: provinding local/task level variables
    vars:
      NAME: "MOKA"
      COURSE: "AWS"
    ansible.builtin.debug:
      msg: "Hi My Name is {{NAME}},I am Learning {{COURSE}} "
      