- name: conditions demo
  hosts: local
  connection: local
  vars_prompt:
  - name: numbers
    prompt: enter the number
    private: false
  tasks:
  - name: print if given number is greater than 20
    ansible.builtin.debug:
      msg: "Given number is greater than 20"
    when: numbers | int > 20 #