- name: creating a user
  hosts: local #entry is made in inventory under [local] localhost
  connection: local #for local server connection
  become: yes #root access
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER #getting the ouput from above command "id expense" into a varible "USER"
    ignore_error: True
  - name: printing from USER
    ansible.builtin.debug:
      msg: "{{USER}}"