- name: installing a list of packages.
  hosts: local
  connection: local
  tasks:
  - name: installing package.
    ansible.builtin.package:
      name: {{item}}
      state: present
    loop:
    - mysql
    - zip
