- name: filters or functionality
  hosts: local
  connection: local
  tasks:
  - name: default variable.
    ansible.builtin.debug:
      msg: "i am learning {{ cast | default('Ansible') }}"
  - name: printing unique set from list
    vars: 
      number: [1,2,3,4,3,21,1,4,67]
    ansible.builtin.debug:
      msg: "unique : {{ number | unique }}"
  - name: printing udifference of  list
    vars: 
      list1: [1,2,3,4,3,21,1,4,67]
      list2: [2,67,4,3,89]
    ansible.builtin.debug:
      msg: "difference of list : {{ list1 | difference(list2) }}"
  - name: printing string in upppercase
    vars:
      greetings: 
      - My Name is Ganesh
      - My Name is Biti
    ansible.builtin.debug:
      msg: "{{ greetings| upper}}"