- name: creating ec2 and r53 
  hosts: local
  connection: local
  tasks:
  - name: creating 3 ec2 instances.
    amazon.aws.ec2_instance:  #module
      name: "{{ item }}"
      vpc_subnet_id:
      instance_type: "t3.micro"
      security_group: 
      image_id:
    loop:
    - mysql
    - backend
    - frontend
    register: ec2-instances

  - name: printing the results.
    ansible.builtin.debug:
      msg: "{{ ec2-instances }}"
