- name: creating ec2 and r53 
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing python dependencies
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9

  - name: creating ec2 instances.
    amazon.aws.ec2_instance:  #module for aws 
      name: "{{ item }}"
      vpc_subnet_id: "subnet-0613c386eba4dff56"  #networks
      instance_type: "t2.micro"
      region: "us-east-1"
      security_group: "sg-077917637fc069d1f"
      image_id: "ami-09c813fb71547fc4f" #ami id
    loop:
    - mysql
    - backend
    - frontend
    register: ec2_instances

  - name: printing the results.
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"
