- name: creating ec2 and r53 
  hosts: local
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    zone: devgani.online
  tasks:
  - name: trying the list1
    ansible.builtin.debug:
      msg: "{{ instances }}"
  - name: trying the list2
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ instances }}"
  