- name: creating ec2 and r53 
  hosts: local
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
  vars_files:
  - vars.yaml
  tasks:
  - name: installing python dependencies
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9

  - name: creating ec2 instances.
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ SUBNET_ID }}" #variable declared in vars.yaml file
      instance_type: "t3.micro"
      security_group: "{{ SECURITY_GROUP }}" #variable declared in vars.yaml file
      image_id: "{{ IMAGE_ID }}" #variable declared in vars.yaml file
      region: "us-east-1"
    loop: "{{ instances }}"
    register: ec2_instances # output assingd to variable ec2_instances
   
  - name: printing the results.
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: creating rout53 records
    amazon.aws.route53:
      state: present
      zone: "devgani.online" # domain name
      record: "{{ item.item }}.devgani.online" #sub domain name
      type: A
      ttl: 1 #refresh time
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: to create a front end public record
    amazon.aws.route53:
      state: present
      zone: "devgani.online" # domain name
      record: "devgani.online" #sub domain name
      type: A
      ttl: 1 #refresh time
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"