- name: creating ec2 and r53 
  hosts: local
  connection: local

  tasks:
  - name: installing python dependencies
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9

  - name: creating ec2 instances.
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "subnet-0613c386eba4dff56"
      instance_type: "t3.micro"
      security_group: "sg-077917637fc069d1f"
      image_id: "ami-09c813fb71547fc4f"
      region: "us-east-1"
    loop: 
    - mysql
    - backend
    - frontend
    register: ec2_instances
   
  - name: printing the results.
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: creating rout53 records
    amazon.aws.route53:
      state: present
      zone: "devgani.online" # domain name
      record: "{{ item.item }}.devgani.online" #sub domain name
      type: A
      ttl: 1 #refresh time
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: to create a front end public record
    amazon.aws.route53:
      state: present
      zone: "devgani.online" # domain name
      record: "devgani.online" #sub domain name
      type: A
      ttl: 1 #refresh time
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"