- name: Terminate instances
  hosts: local
  connection: local
  tasks:
  - name: Terminate instances that were previously launched
    amazon.aws.ec2_instance:
      state: 'absent'
      instance_ids: "{{ item }}"
    loop:
    - "i-082280de2c9297565"
    - "i-0434bbeec4a48e077"
    - "i-02c072d2a12d64ea8"